name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ./Project_SE

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Project_SE
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Project_SE
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Project_SE
